// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudentRegistration.Infrastructure.SqlServer.Persistence;

#nullable disable

namespace StudentRegistration.Infrastructure.SqlServer.Migrations
{
    [DbContext(typeof(StudentRegistrationDbContext))]
    partial class StudentRegistrationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.DataProtection.EntityFrameworkCore.DataProtectionKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FriendlyName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Xml")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DataProtectionKeys", (string)null);
                });

            modelBuilder.Entity("StudentRegistration.Academics.Domain.AcademicTerm", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("CreationClientRequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreationPayloadHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateOnly>("TeachingEndsOn")
                        .HasColumnType("date");

                    b.Property<DateOnly>("TeachingStartsOn")
                        .HasColumnType("date");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("CreationClientRequestId")
                        .IsUnique();

                    b.HasIndex("State", "TeachingStartsOn", "Id");

                    b.HasIndex(new[] { "State" }, "UX_AcademicTerms_OneRegistrationOpen")
                        .IsUnique()
                        .HasFilter("[State] = 'registrationOpen'");

                    b.HasIndex(new[] { "State" }, "UX_AcademicTerms_OneTeaching")
                        .IsUnique()
                        .HasFilter("[State] = 'teaching'");

                    b.ToTable("AcademicTerms", "academics", t =>
                        {
                            t.HasCheckConstraint("CK_AcademicTerms_State", "[State] IN ('draft', 'registrationOpen', 'registrationClosed', 'teaching', 'completed', 'archived')");

                            t.HasCheckConstraint("CK_AcademicTerms_TeachingRange", "[TeachingEndsOn] > [TeachingStartsOn]");
                        });
                });

            modelBuilder.Entity("StudentRegistration.Academics.Domain.RegistrationWindow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ClosesAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("OpensAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ScopeType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("ScopeValue")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<Guid>("TermId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("TermId", "Id");

                    b.HasIndex("TermId", "State", "OpensAtUtc", "ClosesAtUtc");

                    b.ToTable("RegistrationWindows", "academics", t =>
                        {
                            t.HasCheckConstraint("CK_RegistrationWindows_Range", "[ClosesAtUtc] > [OpensAtUtc]");

                            t.HasCheckConstraint("CK_RegistrationWindows_Scope", "([ScopeType] = 'all-students' AND [ScopeValue] IS NULL) OR ([ScopeType] IN ('program', 'cohort') AND [ScopeValue] IS NOT NULL AND LEN(LTRIM(RTRIM([ScopeValue]))) > 0)");

                            t.HasCheckConstraint("CK_RegistrationWindows_State", "[State] IN ('draft', 'published', 'emergencyClosed', 'superseded')");
                        });
                });

            modelBuilder.Entity("StudentRegistration.Academics.Domain.Student", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ApplicationUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Cohort")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("CurrentGpa")
                        .HasPrecision(4, 2)
                        .HasColumnType("decimal(4,2)");

                    b.Property<DateTime>("DataAsOfUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("DataVersion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("EarnedCredits")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)");

                    b.Property<DateTime>("ImportedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ProgramCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SourceReference")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Standing")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId")
                        .IsUnique();

                    b.HasIndex("ProgramCode", "Cohort", "Standing", "Id");

                    b.ToTable("Students", "academics", t =>
                        {
                            t.HasCheckConstraint("CK_Students_CurrentGpa", "[CurrentGpa] >= 0 AND [CurrentGpa] <= 4");

                            t.HasCheckConstraint("CK_Students_EarnedCredits", "[EarnedCredits] >= 0");
                        });
                });

            modelBuilder.Entity("StudentRegistration.Academics.Domain.StudentHold", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("BlocksRegistration")
                        .HasColumnType("bit");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("EffectiveFromUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EffectiveToUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ImportedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SourceReference")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TermId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TermId");

                    b.HasIndex("StudentId", "TermId", "EffectiveFromUtc", "EffectiveToUtc");

                    b.ToTable("StudentHolds", "academics", t =>
                        {
                            t.HasCheckConstraint("CK_StudentHolds_EffectiveRange", "[EffectiveToUtc] IS NULL OR [EffectiveToUtc] > [EffectiveFromUtc]");
                        });
                });

            modelBuilder.Entity("StudentRegistration.Academics.Domain.StudentTermAcademicState", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataAsOfUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("DataVersion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("EarnedCreditsAtStart")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)");

                    b.Property<decimal>("GpaAtStart")
                        .HasPrecision(4, 2)
                        .HasColumnType("decimal(4,2)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SourceReference")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("StandingAtStart")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TermId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("TermId");

                    b.HasIndex("StudentId", "TermId")
                        .IsUnique();

                    b.ToTable("StudentTermAcademicStates", "academics", t =>
                        {
                            t.HasCheckConstraint("CK_StudentTermAcademicStates_EarnedCreditsAtStart", "[EarnedCreditsAtStart] >= 0");

                            t.HasCheckConstraint("CK_StudentTermAcademicStates_GpaAtStart", "[GpaAtStart] >= 0 AND [GpaAtStart] <= 4");
                        });
                });

            modelBuilder.Entity("StudentRegistration.Academics.Domain.TranscriptAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CourseCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Credits")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)");

                    b.Property<string>("GradeCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("ImportedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SourceReference")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SupersedesAttemptId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TermId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SupersedesAttemptId")
                        .IsUnique()
                        .HasFilter("[SupersedesAttemptId] IS NOT NULL");

                    b.HasIndex("TermId");

                    b.HasIndex("StudentId", "CourseCode");

                    b.HasIndex("StudentId", "ImportedAtUtc", "Id");

                    b.ToTable("TranscriptAttempts", "academics", t =>
                        {
                            t.HasCheckConstraint("CK_TranscriptAttempts_Credits", "[Credits] > 0");

                            t.HasCheckConstraint("CK_TranscriptAttempts_NotSelfSuperseding", "[SupersedesAttemptId] IS NULL OR [SupersedesAttemptId] <> [Id]");

                            t.HasCheckConstraint("CK_TranscriptAttempts_Status", "[Status] IN ('in-progress', 'passed', 'failed', 'withdrawn')");
                        });
                });

            modelBuilder.Entity("StudentRegistration.IdentityAccess.Domain.AccountRecoveryChallenge", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ApplicationUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ConsumedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeliveryReferenceHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("FailedAttemptCount")
                        .HasColumnType("int");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("ApplicationUserId", "ExpiresAtUtc", "ConsumedAtUtc");

                    b.ToTable("AccountRecoveryChallenges", "auth");
                });

            modelBuilder.Entity("StudentRegistration.IdentityAccess.Domain.AdminSecurityGuard", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.ToTable("AdminSecurityGuards", "auth", t =>
                        {
                            t.HasCheckConstraint("CK_AdminSecurityGuards_Singleton", "[Id] = 1");
                        });
                });

            modelBuilder.Entity("StudentRegistration.IdentityAccess.Domain.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LockoutEndUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("NormalizedUserName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("SecurityStamp")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("UniversityId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique();

                    b.HasIndex("UniversityId")
                        .IsUnique()
                        .HasFilter("[UniversityId] IS NOT NULL");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.HasIndex("IsEnabled", "LockoutEndUtc");

                    b.ToTable("ApplicationUsers", "auth");
                });

            modelBuilder.Entity("StudentRegistration.IdentityAccess.Domain.AuthenticationAbuseState", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("FailureCount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LockedUntilUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SubjectKeyHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime>("WindowStartedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("SubjectKeyHash")
                        .IsUnique();

                    b.HasIndex("Operation", "LockedUntilUtc");

                    b.ToTable("AuthenticationAbuseStates", "auth");
                });

            modelBuilder.Entity("StudentRegistration.IdentityAccess.Domain.IdentityImportBatch", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ClientRequestId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ErrorSummaryJson")
                        .IsRequired()
                        .HasMaxLength(16000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ImportedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("RequestedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ResultSummaryJson")
                        .HasMaxLength(16000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SourceHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SourceName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("SourceHash")
                        .IsUnique();

                    b.HasIndex("RequestedByUserId", "ClientRequestId")
                        .IsUnique();

                    b.HasIndex("State", "ImportedAtUtc");

                    b.ToTable("IdentityImportBatches", "auth", t =>
                        {
                            t.HasCheckConstraint("CK_IdentityImportBatches_State", "[State] IN ('uploaded', 'invalid', 'validated', 'published', 'failed')");
                        });
                });

            modelBuilder.Entity("StudentRegistration.IdentityAccess.Domain.IdentityImportCandidateRow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ExternalReference")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("IdentityImportBatchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Ordinal")
                        .HasColumnType("int");

                    b.Property<string>("Roles")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("StaffNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UniversityId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UserName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("IdentityImportBatchId", "ExternalReference")
                        .IsUnique();

                    b.HasIndex("IdentityImportBatchId", "Ordinal")
                        .IsUnique();

                    b.ToTable("IdentityImportCandidateRows", "auth");
                });

            modelBuilder.Entity("StudentRegistration.IdentityAccess.Domain.RoleAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ApplicationUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AssignedByReference")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("EffectiveFromUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EffectiveToUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("RoleCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId", "RoleCode", "EffectiveFromUtc")
                        .IsUnique();

                    b.HasIndex("RoleCode", "EffectiveFromUtc", "EffectiveToUtc");

                    b.ToTable("RoleAssignments", "auth", t =>
                        {
                            t.HasCheckConstraint("CK_RoleAssignments_EffectiveRange", "[EffectiveToUtc] IS NULL OR [EffectiveToUtc] > [EffectiveFromUtc]");
                        });
                });

            modelBuilder.Entity("StudentRegistration.IdentityAccess.Domain.SecurityEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ActorReference")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("AfterSummaryJson")
                        .HasMaxLength(8000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ApplicationUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BeforeSummaryJson")
                        .HasMaxLength(8000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MetadataJson")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("SubjectReference")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("CorrelationId");

                    b.HasIndex("EventType", "OccurredAtUtc");

                    b.ToTable("SecurityEvents", "auth");
                });

            modelBuilder.Entity("StudentRegistration.IdentityAccess.Domain.Staff", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ApplicationUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("StaffNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId")
                        .IsUnique();

                    b.HasIndex("StaffNumber")
                        .IsUnique();

                    b.ToTable("Staff", "auth");
                });

            modelBuilder.Entity("StudentRegistration.IdentityAccess.Domain.StudentActivation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ActivatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ApplicationUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("FailedAttemptCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("ProvisionedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId")
                        .IsUnique();

                    b.ToTable("StudentActivations", "auth");
                });

            modelBuilder.Entity("StudentRegistration.Infrastructure.SqlServer.Audit.AuditEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ActorReference")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("AfterSummaryJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BeforeSummaryJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("SubjectReference")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("CorrelationId");

                    b.HasIndex("OccurredAtUtc");

                    b.ToTable("AuditEvents", "audit");
                });

            modelBuilder.Entity("StudentRegistration.Academics.Domain.RegistrationWindow", b =>
                {
                    b.HasOne("StudentRegistration.Academics.Domain.AcademicTerm", null)
                        .WithMany()
                        .HasForeignKey("TermId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("StudentRegistration.Academics.Domain.Student", b =>
                {
                    b.HasOne("StudentRegistration.IdentityAccess.Domain.ApplicationUser", null)
                        .WithOne()
                        .HasForeignKey("StudentRegistration.Academics.Domain.Student", "ApplicationUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("StudentRegistration.Academics.Domain.StudentHold", b =>
                {
                    b.HasOne("StudentRegistration.Academics.Domain.Student", null)
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StudentRegistration.Academics.Domain.AcademicTerm", null)
                        .WithMany()
                        .HasForeignKey("TermId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("StudentRegistration.Academics.Domain.StudentTermAcademicState", b =>
                {
                    b.HasOne("StudentRegistration.Academics.Domain.Student", null)
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StudentRegistration.Academics.Domain.AcademicTerm", null)
                        .WithMany()
                        .HasForeignKey("TermId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("StudentRegistration.Academics.Domain.TranscriptAttempt", b =>
                {
                    b.HasOne("StudentRegistration.Academics.Domain.Student", null)
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StudentRegistration.Academics.Domain.TranscriptAttempt", null)
                        .WithMany()
                        .HasForeignKey("SupersedesAttemptId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("StudentRegistration.Academics.Domain.AcademicTerm", null)
                        .WithMany()
                        .HasForeignKey("TermId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("StudentRegistration.IdentityAccess.Domain.AccountRecoveryChallenge", b =>
                {
                    b.HasOne("StudentRegistration.IdentityAccess.Domain.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("StudentRegistration.IdentityAccess.Domain.IdentityImportBatch", b =>
                {
                    b.HasOne("StudentRegistration.IdentityAccess.Domain.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("RequestedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("StudentRegistration.IdentityAccess.Domain.IdentityImportCandidateRow", b =>
                {
                    b.HasOne("StudentRegistration.IdentityAccess.Domain.IdentityImportBatch", null)
                        .WithMany()
                        .HasForeignKey("IdentityImportBatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("StudentRegistration.IdentityAccess.Domain.RoleAssignment", b =>
                {
                    b.HasOne("StudentRegistration.IdentityAccess.Domain.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("StudentRegistration.IdentityAccess.Domain.SecurityEvent", b =>
                {
                    b.HasOne("StudentRegistration.IdentityAccess.Domain.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("StudentRegistration.IdentityAccess.Domain.Staff", b =>
                {
                    b.HasOne("StudentRegistration.IdentityAccess.Domain.ApplicationUser", null)
                        .WithOne()
                        .HasForeignKey("StudentRegistration.IdentityAccess.Domain.Staff", "ApplicationUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("StudentRegistration.IdentityAccess.Domain.StudentActivation", b =>
                {
                    b.HasOne("StudentRegistration.IdentityAccess.Domain.ApplicationUser", null)
                        .WithOne()
                        .HasForeignKey("StudentRegistration.IdentityAccess.Domain.StudentActivation", "ApplicationUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
