<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\StudentRegistration.Academics\StudentRegistration.Academics.csproj" />
    <ProjectReference Include="..\StudentRegistration.Contracts\StudentRegistration.Contracts.csproj" />
    <ProjectReference Include="..\StudentRegistration.Scheduling\StudentRegistration.Scheduling.csproj" />
  </ItemGroup>

</Project>
