<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.DataProtection.EntityFrameworkCore" Version="10.0.9" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.9" PrivateAssets="all" IncludeAssets="runtime; build; native; contentfiles; analyzers; buildtransitive" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.9" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\StudentRegistration.Academics\StudentRegistration.Academics.csproj" />
    <ProjectReference Include="..\StudentRegistration.Contracts\StudentRegistration.Contracts.csproj" />
    <ProjectReference Include="..\StudentRegistration.IdentityAccess\StudentRegistration.IdentityAccess.csproj" />
    <ProjectReference Include="..\StudentRegistration.Registration\StudentRegistration.Registration.csproj" />
    <ProjectReference Include="..\StudentRegistration.Scheduling\StudentRegistration.Scheduling.csproj" />
    <ProjectReference Include="..\StudentRegistration.StaffAdministration\StudentRegistration.StaffAdministration.csproj" />
  </ItemGroup>

</Project>
