<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>student-registration-local-demo-3df84652b7144a7e92ff92330377ff86</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.9" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Server" Version="10.0.9" />
    <PackageReference Include="Microsoft.OpenApi" Version="2.7.5" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\StudentRegistration.Academics\StudentRegistration.Academics.csproj" />
    <ProjectReference Include="..\StudentRegistration.Client\StudentRegistration.Client.csproj" />
    <ProjectReference Include="..\StudentRegistration.Contracts\StudentRegistration.Contracts.csproj" />
    <ProjectReference Include="..\StudentRegistration.IdentityAccess\StudentRegistration.IdentityAccess.csproj" />
    <ProjectReference Include="..\StudentRegistration.Infrastructure.SqlServer\StudentRegistration.Infrastructure.SqlServer.csproj" />
    <ProjectReference Include="..\StudentRegistration.Registration\StudentRegistration.Registration.csproj" />
    <ProjectReference Include="..\StudentRegistration.Scheduling\StudentRegistration.Scheduling.csproj" />
    <ProjectReference Include="..\StudentRegistration.StaffAdministration\StudentRegistration.StaffAdministration.csproj" />
  </ItemGroup>

</Project>
