<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\StudentRegistration.Academics\StudentRegistration.Academics.csproj" />
    <ProjectReference Include="..\StudentRegistration.Client\StudentRegistration.Client.csproj" />
    <ProjectReference Include="..\StudentRegistration.Contracts\StudentRegistration.Contracts.csproj" />
    <ProjectReference Include="..\StudentRegistration.IdentityAccess\StudentRegistration.IdentityAccess.csproj" />
    <ProjectReference Include="..\StudentRegistration.Infrastructure.SqlServer\StudentRegistration.Infrastructure.SqlServer.csproj" />
    <ProjectReference Include="..\StudentRegistration.Registration\StudentRegistration.Registration.csproj" />
    <ProjectReference Include="..\StudentRegistration.Scheduling\StudentRegistration.Scheduling.csproj" />
    <ProjectReference Include="..\StudentRegistration.StaffAdministration\StudentRegistration.StaffAdministration.csproj" />
  </ItemGroup>

</Project>
